* Core Aesthetics:
** Narrative
** Challenge
** Sense-pleasure
** Exploration
** Fantasy

* Intro hooks
** Mysterious Intro
** Awesomness of world
** Awesomeness of gameplay


Anti-hero becoming apparent almost horror?

* Core Ideas
** Spirituality in a chaotic universe.
   Does the player believe in his companion?
** Is it good that we're even here?

* Characters
  Companion exists as a pattern constructed by a merger of his own nervous system and enhancements.
  Independant entity. Maybe a woman, maybe the temptation later.
  At some point she should be taken away, temporarily or permanently.







* Story
** The call to adventure
   In a prison. We don't reveal how you got into prison. 
   A man covertly hands you some pills to take to 'get out' of prison.

** Refusal of the Call
   You let them clatter to the cell floor.
   Do your own time, take it easy.


** Supernatural Aid
   Some kind of wierd old hippy revolutionary dude
   Get the pillz that empower you with quantum gravitation generation. Magical helper type appears, some kind of hallucination.
   DNA is upgraded to be more baddass, quantum level interactions, cells literally different and smaller, need to eat new minerals (look in to nano-tech)

** The Crossing the First Threshold:
   Use gravity powers to escape the prison.

** Belly of the Whale:
   Go down into the bowels of the prison colony's life-support systems to get into a special escape pod or something.
   Maybe fall down a long chute or something of the like. Companion materializes down here.
   She is made of information you were supposed to get directly, but your brain rejected and isolated?
   We get to the planet surface.

** The Road of Trials:
   You travel over land battling people, forests, cities, deserts, etcetera.
   A gradual change in how the world looks, explained by your companion.
   
   Things look different because of the underlying flux in worlds, or simply hallucinations?

** The Meeting with the Goddess:
   The companion and you grow close.
   Your neurological implants colour your picture of reality.
   You gradually become a weapon as familiarity dissappears.
   In some sense, your implant is literal belief.

** The Woman as Temptress:
   The companion tries to draw you from your quest?
   Ultimately, this would have prevented you from killing yourself.

** Atonement with the Father:
   You were created by the government in some sense, but now transcend it.

** Apotheosis:
   You kill yourself through the linking dimension.
   Regardless of who kills who, you would have died.
   You end up only in the plane of links, maybe with the companion?

** The Ultimate Boon:
   Information. What's going on is revealed.
   You are to be resurrected into the universe in perfect sync, greatly magnifying your power.

** Refusal of Return:
   Exhausted. I want to stay in the whiteness.

** The Magic Flight:
   You can literally fly now using gravity, and you use it to escape.
   Maybe you can generate a continuous wave somehow.

** rescue from without: Companion?

** The Crossing of the Return Threshold:
   Maybe reincarnation via body-swapping tech?

** Master of Two Worlds:
   You are now master of all worlds through the synchronized linking dimension.
   You have become the oscillation of conflict. You are the trans-dimensional archytipical struggle.

** Freedome to Live:


Gravity lensing


In the beginning, you decide to help rebels from in jail. The rebels have been doing well, you help turn the tide and seat them.

You are trying to get to the time-travel engine, as you've heard rumor that they're going to try to send someone back in time to mess up the revolution.

In the middle, you make it to the time-travel engine and succesfully capture it along with the central palace. There is a flash. Someone escapes?

You now continue fighting as it appears the new rebels are close to retaking the castle.

You have become a trans-worldy being.

You have become something of a god of change and revolution.

Time-travel via communication between worlds that have gotten out of sync. Not out of sync. Just the oscillation of conflict.

"There is no such thing as time-travel"

You go save your companion within the linking dimension of which you are now part?

You return to all realities, now a unique entity in all. The first gravity wave you release is of infinite power, and ends time, restarting the universe in the ultimate oscillation.
