* Core Aesthetics:
** Narrative
** Challenge
** Sense-pleasure
** Exploration
** Fantasy

* Intro hooks
** Mysterious Intro
** Awesomness of world
** Awesomeness of gameplay


Anti-hero becoming apparent almost horror?

* Core Ideas
** Spirituality in a chaotic universe.
   Does the player believe in his companion?
** Is it good that we're even here?

* Characters
  Companion exists as a pattern constructed by a merger of his own nervous system and enhancements.
  Independant entity. Maybe a woman, maybe the temptation later.
  At some point she should be taken away, temporarily or permanently.







* Story
** The call to adventure
   In a prison. We don't reveal how you got into prison. 
   A man covertly hands you some pills to take to 'get out' of prison.

** Refusal of the Call
   In some sense you've already refused the call and ended up here.
   You let them clatter to the cell floor.
   Do your own time, take it easy.
   You recieve a phone-call in which you stand still for a long time.
   Then you go to your cell and collect the pills and take them.

** Supernatural Aid
   DNA is upgraded to be more baddass, quantum level interactions, cells literally different and smaller, need to eat new minerals (look in to nano-tech).
   Companion appears, instructs you on how to use the gravity waves.

** The Crossing the First Threshold:
   Use gravity powers to escape the prison.
   Something of a continued tutorial that explains how to play the game subtly.
   
** Belly of the Whale:
   Go down into the bowels of the prison colony's life-support systems to get into a special escape pod or something.
   Maybe fall down a long chute or something of the like. Companion materializes down here.
   She is made of information you were supposed to get directly, but your brain rejected and isolated?
   We get to the planet surface. Escape pod parachutes down over huge, sunny beautiful world.

** The Road of Trials:
   You travel over land battling people, forests, cities, deserts, caves etcetera.
   A gradual change in how the world looks, explained by your companion.
   Things look different because of the underlying flux in worlds, or simply hallucinations?

** The Meeting with the Goddess/Woman as temptress:
   You come to a quite place briefly.
   The companion and you grow close. Some things are explained.
   Your neurological implants colour your picture of reality.
   You gradually become a weapon as familiarity dissappears.
   In some sense, your implant is literal belief.
   The companion tries to draw you from your quest in this place.
   Ultimately, this would have prevented you from killing yourself.

** Atonement with the Father:
   You reach a central city of sorts.
   You come into council, they expect you to be their friend.
   Turns out you are smearing in time, async.
   You were created by the government in some sense, but now transcend it.
   The pills were a plant. 
   
** Apotheosis:
   You kill yourself through the linking dimension.
   Regardless of who kills who, you would have died.
   You end up only in the plane of links, maybe with the companion?

** The Ultimate Boon:
   Information. What's going on is revealed.

** Refusal of Return:
   Exhausted. I want to stay in the whiteness. How to make player feel this?

** Rescue from Without/The Magic Flight/The Crossing of the Return Threshold:
   You are resurrected into the universe in perfect sync, greatly magnifying your power.
   A growing following has built great antennas which connect to the linking dimension.
   You can literally fly now using gravity, and you use it to escape..
   Maybe you can generate a continuous wave somehow.

** Master of Two Worlds:
   You are now master of all worlds through the synchronized linking dimension.
   You have become the oscillation of conflict. You are the trans-dimensional archytipical struggle.

** Freedome to Live:

* Misc 
Gravity lensing


In the beginning, you decide to help rebels from in jail. The rebels have been doing well, you help turn the tide and seat them.

You are trying to get to the time-travel engine, as you've heard rumor that they're going to try to send someone back in time to mess up the revolution.

In the middle, you make it to the time-travel engine and succesfully capture it along with the central palace. There is a flash. Someone escapes?

You now continue fighting as it appears the new rebels are close to retaking the castle.

You have become a trans-worldy being.

You have become something of a god of change and revolution.

Time-travel via communication between worlds that have gotten out of sync. Not out of sync. Just the oscillation of conflict.

"There is no such thing as time-travel"

You go save your companion within the linking dimension of which you are now part?

You return to all realities, now a unique entity in all. The first gravity wave you release is of infinite power, and ends time, restarting the universe in the ultimate oscillation.
