* Gamification
  I want to make the world fun.
  I want to help people to design games that make learning and understanding fun.
  I want to make games take the masses of people who are sad and lonely and watching televesion, and make them happy and contributing.

* Venues
*** Digra (Digital Games Research Association)
*** Academic Mind Trek 
    http://www.academicmindtrek.org/

*** CHI Human Factors in Computing Systems (Good)
*** CGAMES USA
    http://cgamesusa.com/
*** CSCW (Good)
*** CIE (Computers in Entertainment)
*** The Internet and Higher Education
*** Computers and Education (Good)
*** Pervasive Computing, IEEE (Good)

*** CIKM
    http://www.cikm2012.org/

* Resources
** The MIT Center for Collective Intelligence
   http://cci.mit.edu/

* Books

* Crowd-sourcing
** Examples
   Reddit
   StackOverflow
   Wikipedia
   Mechanical Turk
   CrowdFlower
   Innocentive
   
* Related Concepts
** Educational Games
** Serious Games
** Flow
** Games With a Purpose
** Alternate Reality Games
** Augmented Reality Games

** Direction
   Current way is more 'pointsification'
   We want to actually intermingle aestetics and reasons why into the activity. Bring the game into it.
   Some activities are not intrinsically motivating on their own.
   They are big activities that don't break down well into meaningful ones.
   We want to do these activities regardless.

** Modeling fun (Theorem proving approach? 'Fun classes?')
* Human Computation
** Examples
   Doulingo
   Foldit
   GalaxyZoo
   hsx.com
** How do we structure a community for optimal human computation?
** Government

* INTD 325
** Playtesting
*** Q1
**** What was the core idea for the playable prototype?
     What is your game about? If it's a totally abstract game with no connection to or inspiration from reality, tell me that.

**** What are the player experience goals?
     Tell me about how you want your players to feel. What emotions do you wish to evoke? Be more specific than 'Fun'.

**** What is the core mechanic at its heart?
     You have a mechanism that you are testing. Tell me about it. It's OK if the mechanic is presently ill defined - just make that explicit.

*** Q2
**** How does the prototype embody this mechanic?
     What did you build? How is this thing going to test out your core mechanic?

**** What questions did you hope to answer by the playtest?

     Each of your questions should investigate whether your prototype ends up conveying the idea and player-experience goals you've listed in Question 1.
     
     You can also invesigate the mechanical viablitiy of your prototype, but relate these questions to your player experience goals as well. What are you worried won't work? How might that failure frustrate your player experience goals?

*** Q3
**** What did you learn from the playtest?
     Answer your questions! Answer every one of them. Copy and past them from Question 2 first if you have to. If your answer is 'We have no idea', tell me why you got that answer.
     Since your questions are about you player experience goals, at least in part, tell me about how you did. To what extent did you meet your player-experience goals?
     If you have additional insights that you didn't actually ask questions about, list these too.
**** How are you planning to change the game to reach the player experience goals?
     Look at your answers to you questions. Analyze your results and formulate a plan for going forward. What could you do differently? What will stay the same?

* Writing a Proposal
** Background
   Problem
   motivation/importance
   Terminology
   Related work (past and current)
** Objective
   Specific problem definition
** Methodology
   How to do it
   Challenges
** Impact
   What if you succeed?
   Significance
   Novelty
** + Qualifications
   Put it where it makes sense
   you are capable of doing this research
   any good collaborations with known entities

  

* Retroactive human computation

* Lazy Evualuation of Human Resources

* Creating information as fun
** Maybe we can make games that are more fun because of human computation


* CASE THE JOINT
** How do we get people to take good pictures of businesses?
** How do we g


* Computational Model of Fun
** Determine the 'Path' game
*** Shortest path probably isn't fun
*** Hamiltonian path probably isn't fun either
*** This might depend on size of graph


* Mapping the Insides of Buildings
** Need to map buildings to 'defend' them?
** Walking a perimeter
** Attackers exploit mistakes made by mappers
** Attackers exploit cheating by mappers, i.e. incentivize identities staying secret.
** 'The Sea Will Claim Everything'
** Worth considering providing for 3D modeling
** Filters to make images really colourful
** Design roles appealing to women
*** Emotion
    Story? Connect with others
*** Real World
*** Nurturing
    Healing other players
*** Dialog and Verbal Puzzles
    Dialog-based play
*** Learning by example?
*** Multitasking
*** Less competitive

** Denign roles appealing to men
*** Spatial reasoning
*** Destruction
*** Mastery
*** Competion
*** Trial-and-error


** Interesting form of appeal
*** Fantasy
*** Narrative
*** Challenge
*** Fellowship
*** Discovery
*** Expression
*** Submission
*** Gift giving
    Could work well with the point-and-click
*** Humour
    Funny game

*** Possibility
    Lots of choices, like a buffet

*** anticipation

*** Shadenfrued
    
*** Purification
    i.e. pacman, should be doable

*** Thrill

*** Suprise

*** Triumph over Adversity
    Hard, hard stuff.

*** Wonder
    awe and amazement - maybe some kind of high-level business, or abstract or something.

*** Recursive narrative arc



** Journey-esque experience in the real world?
** You take pictures to communicate with another person in real time?

** If windows give us GPS, make windows the target somehow H


* Urban Obstacles
** Gameness
*** 'Unlock' obstacles/courses, they show up on the map as places to go.
    Maybe linear?
** Database 
*** Courses
**** Paths
**** Obstacles
*** obstacles
**** Pics of obstacle
**** GPS location of obstacle
*** classifications
**** parts of body excercised
**** techniques for obstacle



* Money Management Game

* Things to look in to
** CrowdDB
** Qurk
** Turkit
** HProc

* Comparison of mechanical turk algorithms vs game algorithms

* Crowd-source a font on mechanical turk!

* Generalized Crowd-sourcing Platforms

* NFC

* Proposal
** Computational Complexity of Fun
** What have we done before
** lucio icc
** Game Theory?

* User Generated Content

* Applications
** MOOC evaluation

Xuan dominion 1 perudo
kelly powergrid
elvis 
blockus
lost cities jarrod
fiasco
doug wits and wagers


* Affordances Lecture
** State, state-markers, etcetera


* Is it better to have a manager make a bunch of people do things, or a writer create a story that makes them want to do it?


* Proposal
** A section describing the problem, the context/background in which the problem arises, it's importance and similar things
*** Crowdsourcing
*** Human Computation
*** Motivation/Fun
**** Current approach is 'pointsification'
**** Some stumble on inherently interesting problems

** A section characterizing the open computing science challenges that you want to work on and how you are planning to address those, i.e., the research methodology that you are going to apply.
*** Empirical approach
*** Theoretical derivation of principles

** A section highlighting the significance of the contribution that you expect to make if you succeed in your program, addressing what is innovative about your approach.
*** Computational approach to motivation is novel, i.e. what problems are good for humans and how to transform a boring problem to an interesting one.

** A section describing the relationship of your approach to what is known about the problem in the related work literature, in particular mentioning how it will advance the field.
*** Mention number of hours of TV
*** Idea that solving this problem will help with paid version
*** Could also address problem of cheating.

