* Gamification
  I want to make the world fun.
  I want to help people to design games that make learning and understanding fun.
  I want to make games take the masses of people who are sad and lonely and watching televesion, and make them happy and contributing.

* Venues
*** Digra (Digital Games Research Association)
*** Academic Mind Trek
    http://www.academicmindtrek.org/

*** CHI Human Factors in Computing Systems (Good)
*** CGAMES USA
    http://cgamesusa.com/
*** CSCW (Good)
*** CIE (Computers in Entertainment)
*** The Internet and Higher Education
*** Computers and Education (Good)
*** Pervasive Computing, IEEE (Good)



* Crowd-sourcing
** Examples
   Reddit
   StackOverflow
   Wikipedia
* Related Concepts
** Educational Games
** Serious Games
** Flow
** Alternate Reality Games
** Augmented Reality Games

** Direction
   Current way is more 'pointsification'
   We want to actually intermingle aestetics and reasons why into the activity. Bring the game into it.
   Some activities are not intrinsically motivating on their own.
   They are big activities that don't break down well into meaningful ones.
   We want to do these activities regardless.

* Human Computation
** Examples
   Doulingo
   Foldit
** How do we structure a community for optimal human computation?
** Government

* INTD 325
** Playtesting
*** Q1
**** What was the core idea for the playable prototype?
     What is your game about? If it's a totally abstract game with no connection to or inspiration from reality, tell me that.

**** What are the player experience goals?
     Tell me about how you want your players to feel. What emotions do you wish to evoke? Be more specific than 'Fun'.

**** What is the core mechanic at its heart?
     You have a mechanism that you are testing. Tell me about it. It's OK if the mechanic is presently ill defined - just make that explicit.

*** Q2
**** How does the prototype embody this mechanic?
     What did you build? How is this thing going to test out your core mechanic?

**** What questions did you hope to answer by the playtest?

     Each of your questions should investigate whether your prototype ends up conveying the idea and player-experience goals you've listed in Question 1.
     
     You can also invesigate the mechanical viablitiy of your prototype, but relate these questions to your player experience goals as well. What are you worried won't work? How might that failure frustrate your player experience goals?

*** Q3
**** What did you learn from the playtest?
     Answer your questions! Answer every one of them. Copy and past them from Question 2 first if you have to. If your answer is 'We have no idea', tell me why you got that answer.
     Since your questions are about you player experience goals, at least in part, tell me about how you did. To what extent did you meet your player-experience goals?
     If you have additional insights that you didn't actually ask questions about, list these too.
**** How are you planning to change the game to reach the player experience goals?
     Look at your answers to you questions. Analyze your results and formulate a plan for going forward. What could you do differently? What will stay the same?

* Writing a Proposal
** Background
   Problem
   motivation/importance
   Terminology
   Related work (past and current)
** Objective
   Specific problem definition
** Methodology
   How to do it
   Challenges
** Impact
   What if you succeed?
   Significance
   Novelty
** + Qualifications
   Put it where it makes sense
   you are capable of doing this research
   any good collaborations with known entities

   
